const elements={inputSql:document.getElementById('inputSql'),outputSql:document.getElementById('outputSql'),inputMeta:document.getElementById('inputMeta'),outputMeta:document.getElementById('outputMeta'),statusPill:document.getElementById('statusPill'),statusMessage:document.getElementById('statusMessage'),formatBtn:document.getElementById('formatBtn'),copyBtn:document.getElementById('copyBtn'),downloadBtn:document.getElementById('downloadBtn'),clearBtn:document.getElementById('clearBtn'),dialectSelect:document.getElementById('dialectSelect'),indentSize:document.getElementById('indentSize'),keywordCase:document.getElementById('keywordCase'),themeToggle:document.getElementById('themeToggle'),toastStack:document.getElementById('toastStack')};
const SAMPLE_SQL=`select e.employee_id, e.first_name, e.last_name, d.department_name,\n       case when e.salary > 10000 then 'high' else 'standard' end as salary_band\nfrom employees e\njoin departments d on d.department_id = e.department_id\nwhere e.status = 'ACTIVE' and d.location_id in (10, 20, 30)\norder by e.last_name, e.first_name;`;
function initTheme(){const savedTheme=localStorage.getItem('sqlformatter-theme');const theme=savedTheme||'dark';document.documentElement.dataset.theme=theme;elements.themeToggle.textContent=theme==='dark'?'Light mode':'Dark mode'}
function setTheme(theme){document.documentElement.dataset.theme=theme;localStorage.setItem('sqlformatter-theme',theme);elements.themeToggle.textContent=theme==='dark'?'Light mode':'Dark mode'}
function toast(message,type='success'){const item=document.createElement('div');item.className=`toast ${type}`;item.textContent=message;elements.toastStack.appendChild(item);window.setTimeout(()=>item.remove(),2800)}
function updateMeta(textarea,meta){const value=textarea.value;const lines=value?value.replace(/\r\n/g,'\n').replace(/\r/g,'\n').split('\n').length:0;meta.textContent=`${lines} lines | ${value.length} characters`}
function updateAllMeta(){updateMeta(elements.inputSql,elements.inputMeta);updateMeta(elements.outputSql,elements.outputMeta)}
function setStatus(type,message){elements.statusPill.className=`status-pill ${type}`;elements.statusPill.textContent=type==='success'?'Formatted':type==='error'?'Error':'Ready';elements.statusMessage.textContent=message}
function formatSql(){const input=elements.inputSql.value;if(!input.trim()){setStatus('error','Paste SQL before formatting.');toast('Paste SQL before formatting.','error');elements.outputSql.value='';updateAllMeta();return} if(input.length>1024*1024){setStatus('error','Input is larger than the recommended 1 MB browser formatting size.');toast('SQL is larger than the recommended 1 MB size.','error');return}
 try{const formatted=sqlFormatter.format(input,{language:elements.dialectSelect.value,tabWidth:Number(elements.indentSize.value),keywordCase:elements.keywordCase.value,linesBetweenQueries:1});elements.outputSql.value=formatted.trimEnd();updateAllMeta();setStatus('success','SQL formatted successfully.');toast('SQL formatted.')}catch(error){setStatus('error',error.message||'Unable to format the current SQL input.');toast('SQL formatting failed.','error');elements.outputSql.value='';updateAllMeta()}}
async function copyOutput(){if(!elements.outputSql.value){toast('Format SQL before copying output.','error');return}await navigator.clipboard.writeText(elements.outputSql.value);toast('Formatted SQL copied.')}
function downloadOutput(){if(!elements.outputSql.value){toast('Format SQL before downloading.','error');return}const blob=new Blob([elements.outputSql.value],{type:'text/sql;charset=utf-8'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='formatted.sql';link.click();URL.revokeObjectURL(link.href);toast('SQL downloaded.')}
function clearAll(){elements.inputSql.value='';elements.outputSql.value='';setStatus('idle','Paste SQL on the left and run the formatter.');updateAllMeta()}
elements.inputSql.addEventListener('input',updateAllMeta);elements.formatBtn.addEventListener('click',formatSql);elements.copyBtn.addEventListener('click',copyOutput);elements.downloadBtn.addEventListener('click',downloadOutput);elements.clearBtn.addEventListener('click',clearAll);elements.themeToggle.addEventListener('click',()=>setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark'));initTheme();elements.inputSql.value=SAMPLE_SQL;formatSql();
