const elements={patternInput:document.getElementById('patternInput'),sampleText:document.getElementById('sampleText'),highlightOutput:document.getElementById('highlightOutput'),matchesList:document.getElementById('matchesList'),inputMeta:document.getElementById('inputMeta'),matchMeta:document.getElementById('matchMeta'),resultMeta:document.getElementById('resultMeta'),statusPill:document.getElementById('statusPill'),statusMessage:document.getElementById('statusMessage'),testBtn:document.getElementById('testBtn'),copyBtn:document.getElementById('copyBtn'),clearBtn:document.getElementById('clearBtn'),flagG:document.getElementById('flagG'),flagI:document.getElementById('flagI'),flagM:document.getElementById('flagM'),flagS:document.getElementById('flagS'),flagU:document.getElementById('flagU'),themeToggle:document.getElementById('themeToggle'),toastStack:document.getElementById('toastStack')};
const SAMPLE_TEXT=`Contacts:\n- support@devtoolstack.in\n- admin@example.org\n- invalid-at-example\nRequest IDs: DEV-1001 DEV-1002`;
function initTheme(){const savedTheme=localStorage.getItem('regextester-theme');const theme=savedTheme||'dark';document.documentElement.dataset.theme=theme;elements.themeToggle.textContent=theme==='dark'?'Light mode':'Dark mode'}
function setTheme(theme){document.documentElement.dataset.theme=theme;localStorage.setItem('regextester-theme',theme);elements.themeToggle.textContent=theme==='dark'?'Light mode':'Dark mode'}
function toast(message,type='success'){const item=document.createElement('div');item.className=`toast ${type}`;item.textContent=message;elements.toastStack.appendChild(item);window.setTimeout(()=>item.remove(),2800)}
function updateInputMeta(){const value=elements.sampleText.value;const lines=value?value.replace(/\r\n/g,'\n').replace(/\r/g,'\n').split('\n').length:0;elements.inputMeta.textContent=`${lines} lines | ${value.length} characters`}
function setStatus(type,message){elements.statusPill.className=`status-pill ${type}`;elements.statusPill.textContent=type==='success'?'Matched':type==='error'?'Error':'Ready';elements.statusMessage.textContent=message}
function getFlags(){return [elements.flagG.checked?'g':'',elements.flagI.checked?'i':'',elements.flagM.checked?'m':'',elements.flagS.checked?'s':'',elements.flagU.checked?'u':''].join('')}
function escapeHtml(value){return value.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
function renderHighlight(text,matches){if(!matches.length){elements.highlightOutput.textContent=text||'No sample text yet.';return}let html='';let lastIndex=0;for(const match of matches){html+=escapeHtml(text.slice(lastIndex,match.index));html+=`<mark class="match">${escapeHtml(match.value)}</mark>`;lastIndex=match.index+match.value.length}html+=escapeHtml(text.slice(lastIndex));elements.highlightOutput.innerHTML=html}
function testRegex(){const pattern=elements.patternInput.value;if(!pattern){setStatus('error','Enter a regex pattern before testing.');toast('Enter a regex pattern first.','error');elements.highlightOutput.textContent='';elements.matchesList.innerHTML='';elements.matchMeta.textContent='0 matches';return}
 try{const flags=getFlags();const regex=new RegExp(pattern,flags);const text=elements.sampleText.value;const matchList=[];elements.matchesList.innerHTML=''; if(flags.includes('g')){let match;while((match=regex.exec(text))!==null){matchList.push({value:match[0],index:match.index,groups:match.slice(1)});if(match[0]==='') regex.lastIndex+=1}}else{const match=text.match(regex);if(match){const index=text.search(regex);matchList.push({value:match[0],index,groups:match.slice(1)})}}
 renderHighlight(text,matchList);elements.matchMeta.textContent=`${matchList.length} matches`;elements.resultMeta.textContent=matchList.length?`Found ${matchList.length} match${matchList.length===1?'':'es'}`:'No matches found';if(!matchList.length){elements.matchesList.innerHTML='<div class="match-item"><strong>No matches</strong><span>Try adjusting the pattern or flags.</span></div>';setStatus('idle','Pattern is valid, but no matches were found.');return}
 const fragment=document.createDocumentFragment();matchList.forEach((match,idx)=>{const item=document.createElement('div');item.className='match-item';item.innerHTML=`<strong>Match ${idx+1}</strong><div><code>${escapeHtml(match.value)}</code></div><div>Index: ${match.index}</div>${match.groups.length?`<div>Groups: <code>${escapeHtml(JSON.stringify(match.groups))}</code></div>`:''}`;fragment.appendChild(item)});elements.matchesList.appendChild(fragment);setStatus('success',`Pattern is valid and found ${matchList.length} match${matchList.length===1?'':'es'}.`);toast('Regex tested.')}
 catch(error){elements.highlightOutput.textContent='';elements.matchesList.innerHTML='';elements.matchMeta.textContent='0 matches';elements.resultMeta.textContent='Pattern validation failed';setStatus('error',error.message||'Invalid regular expression.');toast('Regex validation failed.','error')}}
async function copyMatches(){const matches=[...elements.matchesList.querySelectorAll('.match-item code')].map(node=>node.textContent);if(!matches.length){toast('Run the regex test before copying matches.','error');return}await navigator.clipboard.writeText(matches.join('\n'));toast('Matches copied.')}
function clearAll(){elements.patternInput.value='';elements.sampleText.value='';elements.highlightOutput.textContent='';elements.matchesList.innerHTML='';elements.matchMeta.textContent='0 matches';elements.resultMeta.textContent='Captured result overview';setStatus('idle','Enter a regex pattern and sample text to inspect matches.');updateInputMeta()}
elements.sampleText.addEventListener('input',updateInputMeta);elements.testBtn.addEventListener('click',testRegex);elements.copyBtn.addEventListener('click',copyMatches);elements.clearBtn.addEventListener('click',clearAll);elements.themeToggle.addEventListener('click',()=>setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark'));initTheme();elements.patternInput.value='\\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,}\\b';elements.flagI.checked=true;elements.sampleText.value=SAMPLE_TEXT;updateInputMeta();testRegex();
